name: Test Repo CI/CD
'on':
  pull_request:
    branches:
      - main
jobs:
  algosec-iac-connectivity-risk-analysis:
    name: Algosec IAC Connectivity Risk Analysis
    runs-on: ubuntu-latest
    container:
      image: 'docker://public.ecr.aws/algosec/connectivity-risk-analysis:1.0.23'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Connectivity Risk Analysis
        run: iac-risk-analysis
        env:
          STOP_WHEN_FAIL: true
          FULL_ANALYSIS: false
          USE_CHECKOUT: true
          ######
          CF_TENANT_ID: ${{ secrets.CF_TENANT_ID }}
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          ######
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          ######
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ######
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          ######
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
